name: Deploy
on:
  workflow_run:
    workflows: ['Run Tests']
    types:
      - completed
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the deploy workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only runs if the triggering 'Run Tests' workflow concluded successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to VPS
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >> ~/.ssh/config <<EOF
          Host my-vps
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          EOF
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Deploy site
        id: deploy
        run: ssh my-vps '${{ secrets.PROJECT_ROOT }}/scripts/redeploy-site.sh'
        continue-on-error: true

      - name: Print Docker container status after deployment
        if: steps.deploy.outcome == 'success'
        run: ssh my-vps 'docker compose -f ${{ secrets.PROJECT_ROOT }}/docker-compose.prod.yml ps'
      
      - name: Send successful result to discord server
        if: steps.deploy.outcome == 'success'
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚀 Deployment Successful"

      - name: Send failure result to discord server
        if: failure()
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Deployment Failed"