name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of tests

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'
      
      - name: Setup Python Virtual Environment
        run: python -m venv site_env
      
      - name: Install Dependencies
        run: site_env/bin/pip install -r requirements.txt
      
      - name: Run Tests
        run: ./scripts/run_test.sh